import React, { FunctionComponent } from "react";
import { Container, Breadcrumb } from "react-bootstrap";
import { Link } from "react-router-dom";

export const HowToCite: FunctionComponent = () => {
  return (
    <Container className="mt-5 mb-5">
      <h1 className="mb-5">How to acknowledge 3i in publications</h1>
      <Breadcrumb className="bg-white">
        <Breadcrumb.Item>
          <Link to="/">Home</Link>
        </Breadcrumb.Item>
        <Breadcrumb.Item>
          <Link to="/project/">Project</Link>
        </Breadcrumb.Item>
        <Breadcrumb.Item active>How to cite?</Breadcrumb.Item>
      </Breadcrumb>
      <p>
        All publications that mainly contain data funded by 3i (e.g.
        descriptions and results of individual screens, work undertaken by
        3i-funded researchers) should have &ldquo;the 3i consortium&rdquo; as an
        author. Contact project manager Lucie Abeler-D&ouml;rner for an
        up-to-date list of names behind the consortium name&nbsp;
        <a href="mailto:lucie.abeler-dorner@bdi.ox.ac.uk">Send email</a>.
      </p>
      <p>
        All publications that contain work that was directly funded by the 3i
        grant should acknowledge the grants as follows: &ldquo;This project was
        supported by Wellcome Trust grant [100156]
        (www.immunophenotype.org).&rdquo; Feel free to add more specifics (e.g.
        who or which part was funded/supported).
      </p>
      <p>
        All publications that use data or protocols generated by 3i should
        acknowledge the grant is follows: &ldquo;This project used
        data/protocols generated by the 3i consortium (www.immunophenotype.org);
        Wellcome Trust grant [100156].&rdquo;
      </p>
    </Container>
  );
};
